#version: 2
#sources:
#  - name: jaffle_shop
#    description: This is a replica of the Postgres database used by out app
#    database: dbt-tutorial
#    schema: jaffle_shop
#    tables:
#      - name: customers
#        description: One record per customer
#      - name: orders
#        description: One record per order. Includes cancelled and deleted orders
#  - name: stripe
#    description: Stripe db
#    database: dbt-tutorial
#    schema: stripe
#    tables:
#      - name: payment
#        description: payments info
